// Generated by scripts/sync-arc1-metrics.mjs from Models/arc1_arc1_tiny.metrics.json. Do not edit.
export const ARC1_METRICS = {
  "rcn": {
    "file": "/api/arc1-download",
    "bytes": 769344,
    "sha256": "ae5777fabd0e653be010ce392ccba753f0f5718b426bfcdd003bdcdc00e154e9",
    "quant": "rq4"
  },
  "formats": [
    {
      "label": "Keras weights, f32",
      "bytes": 5465216,
      "exactCall": 0.907,
      "extractF1": 0.982
    },
    {
      "label": ".rcn f16",
      "bytes": 2653440,
      "exactCall": 0.907,
      "extractF1": 0.982
    },
    {
      "label": "TFLite int8",
      "bytes": 1791192,
      "exactCall": null,
      "extractF1": null
    },
    {
      "label": ".rcn rq8",
      "bytes": 1425088,
      "exactCall": 0.907,
      "extractF1": 0.982
    },
    {
      "label": ".rcn rq4",
      "bytes": 769344,
      "exactCall": 0.913,
      "extractF1": 0.981
    }
  ],
  "parameters": 1320067,
  "cycles": 3,
  "seqLen": 160,
  "latencyP50Ms": 7.77,
  "fireEceBefore": 0.004823492260179441,
  "fireEceAfter": 0.0030744145312907706,
  "n": {
    "tools": 300,
    "unseenTools": 150,
    "extraction": 150,
    "classify": 150,
    "calibrationFire": 749
  },
  "retrievalAt1": 1,
  "byCycles": [
    {
      "cycles": 1,
      "toolSelection": 0.9933333333333333,
      "exactCall": 0.93,
      "argumentAcc": 0.9321148825065274,
      "noToolAcc": 1,
      "exactCallUnseen": 0.29333333333333333,
      "toolSelectionUnseen": 0.4266666666666667,
      "extractionF1": 0.9856115107913669,
      "exactRecord": 0.9533333333333334,
      "classifyOverall": 0.6866666666666666,
      "classifyIntent": 1,
      "classifyIntentTool": 1,
      "classifyRequest": 1,
      "classifySentiment": 0.6896551724137931,
      "classifySupport": 0.5185185185185185,
      "classifyUnseen": 0.3333333333333333,
      "classifyProducts": 0.2727272727272727,
      "classifyFeed": 0.625,
      "classifySearch": 0.6666666666666666,
      "latencyP50Ms": 9.43
    },
    {
      "cycles": 3,
      "toolSelection": 0.99,
      "exactCall": 0.9233333333333333,
      "argumentAcc": 0.9242819843342036,
      "noToolAcc": 1,
      "exactCallUnseen": 0.2866666666666667,
      "toolSelectionUnseen": 0.4,
      "extractionF1": 0.9808153477218226,
      "exactRecord": 0.9333333333333333,
      "classifyOverall": 0.68,
      "classifyIntent": 1,
      "classifyIntentTool": 1,
      "classifyRequest": 1,
      "classifySentiment": 0.7241379310344828,
      "classifySupport": 0.5185185185185185,
      "classifyUnseen": 0.36,
      "classifyProducts": 0.2727272727272727,
      "classifyFeed": 0.625,
      "classifySearch": 0.5833333333333334,
      "latencyP50Ms": 7.77
    }
  ]
} as const;
