// Generated by scripts/sync-arc1-metrics.mjs from Models/arc1_arc1_tiny.metrics.json. Do not edit.
export const ARC1_METRICS = {
  "rcn": {
    "file": "/models/arc1-tiny.rcn",
    "bytes": 769344,
    "sha256": "e3242f0686600b33e10e36955302251c124cf1de0c00eb02bd50c1bc7c77d9fc",
    "quant": "rq4"
  },
  "formats": [
    {
      "label": "Keras weights, f32",
      "bytes": 5465216,
      "exactCall": 0.887,
      "extractF1": 0.972
    },
    {
      "label": ".rcn f16",
      "bytes": 2653440,
      "exactCall": 0.887,
      "extractF1": 0.972
    },
    {
      "label": "TFLite int8",
      "bytes": 1791192,
      "exactCall": null,
      "extractF1": null
    },
    {
      "label": ".rcn rq8",
      "bytes": 1425088,
      "exactCall": 0.887,
      "extractF1": 0.972
    },
    {
      "label": ".rcn rq4",
      "bytes": 769344,
      "exactCall": 0.893,
      "extractF1": 0.968
    }
  ],
  "parameters": 1320067,
  "cycles": 3,
  "seqLen": 160,
  "latencyP50Ms": 5.62,
  "fireEceBefore": 0.009473739809061103,
  "fireEceAfter": 0.00936292339294883,
  "retrievalAt1": 1,
  "byCycles": [
    {
      "cycles": 1,
      "toolSelection": 0.9733333333333334,
      "exactCall": 0.8966666666666666,
      "argumentAcc": 0.9112271540469974,
      "noToolAcc": 0.9682539682539683,
      "exactCallUnseen": 0.3333333333333333,
      "extractionF1": 0.9747899159663866,
      "classifyIntent": 1,
      "classifySentiment": 0.673469387755102,
      "classifySupport": 0.4888888888888889,
      "classifyUnseen": 0.4533333333333333,
      "latencyP50Ms": 5.4
    },
    {
      "cycles": 3,
      "toolSelection": 0.98,
      "exactCall": 0.8933333333333333,
      "argumentAcc": 0.9112271540469974,
      "noToolAcc": 0.9841269841269841,
      "exactCallUnseen": 0.31333333333333335,
      "extractionF1": 0.96875,
      "classifyIntent": 1,
      "classifySentiment": 0.673469387755102,
      "classifySupport": 0.4666666666666667,
      "classifyUnseen": 0.48,
      "latencyP50Ms": 5.62
    }
  ]
} as const;
