// Generated by scripts/sync-arc1-metrics.mjs from Models/arc1_arc1_tiny.metrics.json. Do not edit.
export const ARC1_METRICS = {
  "rcn": {
    "file": "/api/arc1-download",
    "bytes": 771520,
    "sha256": "8b078f4412c65544fd321a6149f651048053b01c8c96d00b1459c97eff9e66c9",
    "quant": "rq4"
  },
  "formats": [
    {
      "label": "Keras weights, f32",
      "bytes": 5468928,
      "exactCall": 0.867,
      "extractF1": 0.975
    },
    {
      "label": ".rcn f16",
      "bytes": 2655680,
      "exactCall": 0.86,
      "extractF1": 0.975
    },
    {
      "label": "TFLite int8",
      "bytes": 1794008,
      "exactCall": null,
      "extractF1": null
    },
    {
      "label": ".rcn rq8",
      "bytes": 1427264,
      "exactCall": 0.86,
      "extractF1": 0.975
    },
    {
      "label": ".rcn rq4",
      "bytes": 771520,
      "exactCall": 0.867,
      "extractF1": 0.972
    }
  ],
  "parameters": 1320835,
  "cycles": 3,
  "seqLen": 160,
  "latencyP50Ms": 2.5,
  "fireEceBefore": 0.006771185702113762,
  "fireEceAfter": 0.006021034886946575,
  "n": {
    "tools": 300,
    "unseenTools": 150,
    "extraction": 150,
    "classify": 150,
    "calibrationFire": 749
  },
  "retrievalAt1": 1,
  "realIntents": {
    "accuracy": 0.5766666666666667,
    "n": 600,
    "labels": 5,
    "chance": 0.2
  },
  "byCycles": [
    {
      "cycles": 1,
      "toolSelection": 0.9833333333333333,
      "exactCall": 0.85,
      "argumentAcc": 0.8485639686684073,
      "noToolAcc": 1,
      "exactCallUnseen": 0.4,
      "toolSelectionUnseen": 0.4866666666666667,
      "extractionF1": 0.9648484848484848,
      "exactRecord": 0.8666666666666667,
      "classifyOverall": 0.7533333333333333,
      "classifyIntent": 1,
      "classifyIntentTool": 1,
      "classifyRequest": 1,
      "classifySentiment": 0.6896551724137931,
      "classifySupport": 0.6296296296296297,
      "classifyUnseen": 0.64,
      "classifyProducts": 0.6363636363636364,
      "classifyFeed": 0.625,
      "classifySearch": 0.6666666666666666,
      "latencyP50Ms": 2.51
    },
    {
      "cycles": 3,
      "toolSelection": 0.9833333333333333,
      "exactCall": 0.86,
      "argumentAcc": 0.8590078328981723,
      "noToolAcc": 1,
      "exactCallUnseen": 0.38666666666666666,
      "toolSelectionUnseen": 0.49333333333333335,
      "extractionF1": 0.9662650602409639,
      "exactRecord": 0.88,
      "classifyOverall": 0.7466666666666667,
      "classifyIntent": 1,
      "classifyIntentTool": 1,
      "classifyRequest": 1,
      "classifySentiment": 0.6551724137931034,
      "classifySupport": 0.7037037037037037,
      "classifyUnseen": 0.6266666666666667,
      "classifyProducts": 0.5454545454545454,
      "classifyFeed": 0.5,
      "classifySearch": 0.5833333333333334,
      "latencyP50Ms": 2.5
    }
  ]
} as const;
